sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: wjr107024
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: 
    access-key-secret: 
    bucket-name: wangsansi
  redis:
    host: localhost
    port: 6379
    password: wjr107024
    database: 0
  wechat:
    appid: wxa5b8034b06aaebfa
    secret: 70ce423e739ab13cddcf3800c90c0493