sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: wjr107024
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tLhJUkNNF3akkU6G4Sn
    access-key-secret: ZLQdB0ZldWdw4yrfNNdS7nWiMNfqsY
    bucket-name: wangsansi
