server:
  port: 8080

spring:
  profiles:
    active: dev # 将application-dev.yml中的配置激活, 在那个配置中的配置的是与数据库进行连接的相关配置, 以及使用的mysql驱动, 这里使用的是drive-class-name属性进行指定, 在配置阿里OSS的使用使用的也是dev环境下的配置
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  redis: # 将redis的相关配置文件写在Spring的配置文件中, 这样就可以使用Spring的注解进行注入
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    password: ${sky.redis.password}
    database: ${sky.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  #开启包扫描, 开启后可以不使用完整包名只使用最后的包名也就是类名
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间, token有效期这里使用的是ms毫秒转换为s秒就是7200s, 也就是token的有效期为两个小时
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    # 设置用户端的jwt
    user-secret-key: itheima
    user-ttl: 7200000
    user-token-name: authentication #这里的token-name是前端传递过来的令牌名称, 也就是前端传递过来的令牌名称必须是authentication, 和前端之间的数据达成约定
  # 自定义属性,在配置属性类AliOssProperties使用注解@ConfigurationProperties(prefix = "sky.ali-oss")进行注入
  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}
  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}
    shop:
      address: 北京市海淀区上地十街
    baidu:
      ak: 3p49MVra6urFRGOT9s8UBWr2
      sk: 3s2q1Grw6bq074Cb8eB4oGyxxrTULs7e